export const tabsData = [
  { label: 'Dashboard', id: '1' },
  { label: 'Banking', id: ' 2' },
  { label: 'Telefonie', id: ' 3' },
  { label: 'Accounting', id: ' 4' },
  { label: 'Verkauf', id: ' 5' },
  { label: 'Statistik', id: ' 6' },
  { label: 'Post Office', id: ' 7' },
  { label: 'Administration', id: ' 8' },
  { label: 'Help', id: ' 9' },
  { label: 'Warenbestand', id: ' 10' },
  { label: 'Auswahllisten', id: ' 11' },
  { label: 'Einkauf', id: ' 12' },
  { label: 'Lagerverwaltung', id: ' 13' },
  { label: 'Verkauf', id: ' 14' },
  { label: 'Post Office', id: ' 15' },
  { label: 'Telefonie', id: ' 16' },
];
